project:
  type: website
  output-dir: docs
website:
  title: "Erica Adezati"
  navbar:
    right:
      - about.qmd
      - Projects.qmd
      - Teaching.qmd
      - Contacts.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/erica-adezati
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



